version: '3.8'
services:
  app:
    build:
      context: .
      target: build-stage
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
